cc_binary(
    name = "server",
    srcs = [
        "server.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//core/lexer",
        "//core/parser",
        "@boost",
    ],
)
