cc_library(
    name = "ir",
    srcs = [
        "ir.cpp",
    ],
    hdrs = [
        "ir.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//core/parser",
        "//core/parser:node",
        "//core/util:buffer",
        "//core/util:diagnostics",
    ],
)
