cc_library(
    name = "llvmir",
    srcs = [
        "llvmir.cpp",
    ],
    hdrs = [
        "llvmir.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//core/ir",
        "//core/util:diagnostics",
        "@llvm",
    ],
)
