cc_library(
    name = "buffer",
    hdrs = ["buffer.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "diagnostics",
    hdrs = ["diagnostics.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":source",
    ],
)

cc_library(
    name = "enum",
    hdrs = ["enum.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "source",
    hdrs = ["source.h"],
    visibility = ["//visibility:public"],
)
